### ISSUE TITLE
这个在mac上提示“将对您的电脑造成伤害，您应该将它移到废纸篓”

### ISSUE THREAD

**Issue by cosbetas** [paradiseduo/ClashXR#1]
提示“将对您的电脑造成伤害，您应该将它移到废纸篓”
通过“覆盖恶意软件保护”修改后仍无法打开

**Comment by paradiseduo** [comment]
系统版本呢？我估计是个人证书签名的问题，这个目前没有好的解决方法，我手上没有可以用的公司证书。你要么就开启“任何来源”
```
sudo spctl –master-disable
```

**Comment by cosbetas** [comment]
x系统版本10.15.3 任何来源已开启 重新签名后 无法安装服务 一直用不成啊

**Comment by paradiseduo** [comment]
> x系统版本10.15.3 任何来源已开启 重新签名后 无法安装服务 一直用不成啊

不要重签名

**Comment by cosbetas** [comment]
新版本已经可以使用
