### ISSUE TITLE
看到警告信息并且无法打开应用

### ISSUE THREAD

**Issue by singworld** [paradiseduo/ClashXR#11]
![image](https://user-images.githubusercontent.com/37404619/82621580-11c7bf80-9c0e-11ea-80de-e9ec73e6d8bb.png)
https://support.apple.com/zh-cn/HT202491
手动信任也没法点了

**Comment by paradiseduo** [comment]
你能开启允许任何来源之后再试试吗？
```
sudo spctl –master-disable
```

**Comment by singworld** [comment]
解决了  刚准备来关   解决方式有两种 一种是开启任何来源sudo spctl –master-disable  还有一种是首次在finder中右键打开
