### ISSUE TITLE
从ShadowsocksX-NG-R8来跟随大佬的步伐

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ClashXR#12]
大佬，clashxr可以不转换订阅链接直接用ssr或V2ray的订阅链接来获取节点么😂🤣

**Comment by paradiseduo** [comment]
暂时不能，clash本身必须要有节点和规则配合才可以使用，仅有节点是无法使用的。
而且对于clashxr我并不打算另行开发，只是在原本clashx的基础上增加了对SSR的支持。
clash core一直说要支持SSR，结果到现在也没合并到主分支上，等哪天clash core支持SSR，那这个项目也就不需要维护，大家都用clashx就好了。

**Comment by Sam-Caesarmat** [comment]
> 暂时不能，clash本身必须要有节点和规则配合才可以使用，仅有节点是无法使用的

好把

**Comment by paradiseduo** [comment]
而且我认为将来模仿HTTPS流量才是扶墙的出路，SSR和SS注定会被淘汰的。
Trojan跟V2ray的WebSocks+TLS+Web，然后配合CDN节点防止IP被封锁。
