### ISSUE TITLE
添加ssr订阅后提示格式错误

### ISSUE THREAD

**Issue by noood** [paradiseduo/ClashXR#13]
<img width="420" alt="1" src="https://user-images.githubusercontent.com/8966024/82719404-f37cc500-9cdc-11ea-9846-6e0dcbf3ff0d.png">

**Comment by paradiseduo** [comment]
密码或者其他参数里不要包含引号分号斜杠反斜杠等字符

**Comment by noood** [comment]
> 密码或者其他参数里不要包含引号分号斜杠反斜杠等字符

是我的操作方式不对吗？SSR订阅链接都会有斜杠的吧？

**Comment by paradiseduo** [comment]
ssr的订阅链接无法直接使用，需要用转换器转换成clash的规则文件才可以。你可以找一个规则文件托管服务器转换，也可以用我的[subweb](https://github.com/paradiseduo/subweb)项目自己搭建一个本地转换器。
