### ISSUE TITLE
Mac更新到10.15之后clashXR莫名的选择节点的proxy消失不见了

### ISSUE THREAD

**Issue by Kesigner** [paradiseduo/ClashXR#15]
Mac更新到10.15之后clashXR莫名的选择节点的proxy消失不见了，是这一两天出现的问题，前几天在10.15版本Mac也是可用的，从昨天出现的问题，我在虚拟机10.13测试是没有问题的，作者大大
是否更新呢，我查看到clashX已经更新到了1.20.2

**Comment by paradiseduo** [comment]
你能截个图吗？

**Comment by Kesigner** [comment]
![微信图片编辑_20200606121503](https://user-images.githubusercontent.com/39486149/83935781-74fd4880-a7ef-11ea-95d1-241eefc37b35.jpg)
<img width="200" alt="微信图片_20200606121533" src="https://user-images.githubusercontent.com/39486149/83935782-76c70c00-a7ef-11ea-9802-3d21e7c14fa4.png">

**Comment by Kesigner** [comment]
谢谢作者大大回复，就和上图一样，配置已经导入，但是没有节点选项，导入时显示导入成功提示。我在Mac10.13是可以操作的。

**Comment by paradiseduo** [comment]
你检查一下配置文件夹里，规则文件里面有东西吗

**Comment by Kesigner** [comment]
我好像找到问题在哪了，是这样的我刚才看了一下配置文件，是有的，配置文件里也是有节点信息的。但是我看到在配置文件里导入链接为clash=1而在配置管理那里，就是我导入的链接是clash=2，我把配置文件里的1改成2就好了。就出来节点了，什么原因会导致配置链接与配置文件里不一致
<img width="359" alt="5998C280-F4A2-4D26-A828-DD7726463316" src="https://user-images.githubusercontent.com/39486149/83946288-6b510080-a842-11ea-8ecb-0672641eb4b4.png">
![43668A3B-31C6-4BFA-BEBE-F88B4F77B7EA](https://user-images.githubusercontent.com/39486149/83946290-6db35a80-a842-11ea-99df-969af035b2c5.jpeg)
![8850E20D-A058-4BBE-818E-26EA753D8B1B](https://user-images.githubusercontent.com/39486149/83946292-6f7d1e00-a842-11ea-8bc8-df0c257dfa43.jpeg)

**Comment by paradiseduo** [comment]
这个。。你不主动改它应该不会变啊。

**Comment by Kesigner** [comment]
嗯好的，谢谢作者大大，我再观察一下，因为是同时出现了两个用户有这个问题，现在改完是没有问题的，感谢！

**Comment by Kesigner** [comment]
作者大大，有一个还是不行，确信。不知道啥原因，当我改完配置文件里的clash=1改为clash=2之后，保存修改配置，再进行更新的时候，配置文件又会被重写为clash=1，而托管链接哪里是2。就是改完更新，配置文件哪里也还是会重写为1，我崩溃了，哈哈

**Comment by paradiseduo** [comment]
你直接在浏览器里访问托管地址，看返回的是什么

**Comment by mrxiaomitian** [comment]
> 作者大大，有一个还是不行，确信。不知道啥原因，当我改完配置文件里的clash=1改为clash=2之后，保存修改配置，再进行更新的时候，配置文件又会被重写为clash=1，而托管链接哪里是2。就是改完更新，配置文件哪里也还是会重写为1，我崩溃了，哈哈
我也碰到这个问题了，请问解决了吗，配置文件里确实有节点，但是就是在软件里显示不出来。

**Comment by mrxiaomitian** [comment]
我在浏览器里访问托管地址，返回的是节点。但是软件里就是不显示啊，不知道怎么解决，能帮忙吗

**Comment by paradiseduo** [comment]
> 我在浏览器里访问托管地址，返回的是节点。但是软件里就是不显示啊，不知道怎么解决，能帮忙吗

你在配置文件的列表切换一下配置才会在菜单里刷新
