### ISSUE TITLE
关于clash闭源内核的通知

### ISSUE THREAD

**Issue by paradiseduo** [paradiseduo/ClashXR#19]
![image](https://user-images.githubusercontent.com/14846965/84873603-115c0080-b0b6-11ea-96f2-950b76262e80.png)
由于开源版 Clash 内核功能欠缺 
Clash for Android 开源版本今后将只进行稳定性更新
不再添加任何新特性 仅修理 Bug 和 更新 Clash Core
接下来将转向开发 使用 Clash 闭源内核 的 Clash for Android Pro
根据上游 Clash 开发者的授权协议 Clash for Android Pro 也将 保持闭源
Clash for Android Pro 同 ClashX Pro 类似
仅仅为使用闭源内核的分支
不会收取任何费用
闭源内核特性参见 https://github.com/Dreamacro/clash/releases/tag/premium

由于上游的原因，此项目今后可能不再维护（如果clashx开源分支有更新，可能会再合并过来），大家之后可以将ClashX Pro与ShadowsocksX-NG-R配合使用，达到ClashXR的效果（也可以放弃SSR协议，转向v2ray或者trojan）。
具体配置大概像这样：
首先将ShadowsocksX-NG-R设置为手动模式。
然后编辑clash的配置文件保存，然后在clashx里刷新一下即可：
```
Proxy:
# name：随意，我这里是 socks;
# type：不可更改
# server：一般本地都是这个地址
# port：这里的端口填写 ShadowsocksX-NG-R 里高级设置的本地 socks5 监听端口

# socks5
- { name: "socks", type: socks5, server: 127.0.0.1, port: 1086 }

Proxy Group:
# name：依据 Rule 所对应的修改
# type：不可更改
# proxies：不可更改

# select
- { name: "Proxy", type: select, proxies: ["socks"] }
```
大概的原理就是先使用clash的规则分流，翻墙的流量走ShadowsocksX-NG-R，流量走的socks5协议（http也行，但是建议用socks5）。

两款软件如此设置以后，如果你此时把 ShadowsocksX-NG-R 退出，然后再打开ShadowsocksX-NG-R，这时代理是不起作用的，clashx也没作用。
解决办法是把 clashX 里的系统代理关闭，然后再打开，就可以走流量了。

**Comment by stimw** [comment]
用两个软件感觉有点麻烦...希望可以继续维护吧
Clash还不支持ssr就很无语，虽然我用的只支持ssr的机场也很无语...

**Comment by Sam-Caesarmat** [comment]
大佬，有没有ClashX Pro的地址
