### ISSUE TITLE
用浏览器下载文件时，时常断开连接

### ISSUE THREAD

**Issue by nocrizwang** [paradiseduo/ClashXR#2]
使用浏览器下载一个几MB大小的文件，下载了几次，都是下载到一半就断开连接需要从头下载。使用SSR和直连均无此问题。

**Comment by nocrizwang** [comment]
嗯……使用之前的SSR客户端和不使用代理直连均无问题

**Comment by paradiseduo** [comment]
是不是开了自动选择节点？

**Comment by nocrizwang** [comment]
开的全局模式，应该不是自动选择吧？

**Comment by paradiseduo** [comment]
这个我也不是很清楚，你只有SSR的节点吗？试一试v2ray之类的会不会断
