### ISSUE TITLE
ports open fail, please try to restart clashx

### ISSUE THREAD

**Issue by LeslieYang6** [paradiseduo/ClashXR#23]
不能成功打开，打开时出现这个！

**Comment by paradiseduo** [comment]
try release 1.30.0, and check if 7890 pors has been used by other process.

**Comment by LeslieYang6** [comment]
I have killed the process using 7890 and i am using 1.30.0, but i get the same result,ports open fail.

**Comment by paradiseduo** [comment]
由于clash原生库支持ssr，clashxr正式推出历史舞台，不再维护。
