### ISSUE TITLE
不支持macOS内置邮件发gmail邮件

### ISSUE THREAD

**Issue by fatrnick** [paradiseduo/ClashXR#25]

**Comment by paradiseduo** [comment]
本项目已停止维护，建议使用clashx pro的增强模式

**Comment by fatrnick** [comment]
抱歉，可惜clashx pro不支持ssr

**Comment by paradiseduo** [comment]
> 抱歉，可惜clashx pro不支持ssr

已经支持了

**Comment by fatrnick** [comment]
那就是我ssr有问题了 读不出节点。。。

**Comment by paradiseduo** [comment]
> 那就是我ssr有问题了 读不出节点。。。

配置文件需要更新，格式变了，转换链接（隐私问题自行考虑）：
https://acl4ssr.netlify.app/

因为和ClashR的字段不同，如果你是用的SSR订阅
请使用 『Clash新参数』转换订阅
转换地址：https://acl4ssr.netlify.app/

Clash的SSR新参数与ClashR参数的区别在于 protocolparam 和 obfsparam 的不同
ClashR是「protocolparam」和「obfsparam」
Clash新参数是「protocol-param」和「obfs-param」

Clash SSR 支持的加密方式如下：
AES_128_GCM
AES_192_GCM
AES_256_GCM
AEAD_CHACHA20_POLY1305
XCHACHA20_POLY1305
RC4-MD5
AES-128-CTR
AES-192-CTR
AES-256-CTR
AES-128-CFB
AES-192-CFB
AES-256-CFB
CHACHA20-IETF
XCHACHA20

**Comment by fatrnick** [comment]
谢谢！
