### ISSUE TITLE
睡眠启动之后卡顿

### ISSUE THREAD

**Issue by lyhxiangyang** [paradiseduo/ClashXR#26]
# 睡眠之后卡顿
当MAC黑屏之后，等待10min或者更长时间，按任意键，电脑屏幕亮起，指纹解锁，我发现鼠标有10s左右时间无法移动，触摸板无法操作，10s之后，一切恢复正常。经过我长时间排查之后，是我们的clashXR软件问题。
我猜想是否和硬盘睡眠有关系。

**Comment by paradiseduo** [comment]
**The maintenance of this project has been terminated due to force majeure. It is recommended to feed back to the clashX project. Thank you for your understanding.**
