### ISSUE TITLE
相同trojan的节点, 在ios端用QuanX正常打开外网, Mac端用clashxr就不行

### ISSUE THREAD

**Issue by Jacob-pixil** [paradiseduo/ClashXR#3]

**Comment by paradiseduo** [comment]
试试clashx，这个分支跟clashx唯一的区别就是支持ssr，如果不用ssr的话建议使用clashx

**Comment by Jacob-pixil** [comment]
订阅的机场有ssr的线路, clashx也不行, 不行就算了吧, 可能目前版本不支持

**Comment by paradiseduo** [comment]
> 订阅的机场有ssr的线路, clashx也不行, 不行就算了吧, 可能目前版本不支持

那应该是clash底层库的问题，我在clashx的issues里也看到有人反馈Trojan不好使了https://github.com/yichengchen/clashX/issues/298

你可以试试这个项目https://github.com/paradiseduo/Trojan
不支持订阅，但这是完全基于trojan原生二进制的客户端
