### ISSUE TITLE
“ClashXR” will damage your computer. You should move it to the Bin. 下载后无法打开。

### ISSUE THREAD

**Issue by FrankYip1020** [paradiseduo/ClashXR#4]
<img width="542" alt="Screenshot 2020-05-07 at 11 25 47 AM" src="https://user-images.githubusercontent.com/34473788/81251328-95ea4680-9055-11ea-8d69-2a8fe9e470f1.png">

**Comment by paradiseduo** [comment]
#1

**Comment by FrankYip1020** [comment]
任何来源已开启，最新版本也打开不了

**Comment by paradiseduo** [comment]
重新下载一下试试，我重打包了。
没办法，免费的个人证书就是这样，我手上没有付费的开发者证书。

**Comment by FrankYip1020** [comment]
现在可以了，谢谢
