### ISSUE TITLE
关于软件打不开，系统提示移到废纸篓

### ISSUE THREAD

**Issue by paradiseduo** [paradiseduo/ClashXR#5]
大概就像这样：
![image](https://user-images.githubusercontent.com/14846965/81311511-1346a300-90b8-11ea-8567-902be3c4207a.png)

可以在这里留言，我会尽快重新打包。

原因是这样，由于我比较穷，买不起苹果99$一年的开发者证书，因此使用的苹果免费证书。
然而苹果的免费证书只能让一个软件从打包开始算起，正常运行7天。
超过七天，就会提示像损害电脑啦，程序意外退出啦，这样的现象。

我正在努力的搬砖。。争取早点买得起99$的证书。。

------ ⚠️好消息好消息⚠️ ------
通过`轻松愉悦`的PY交易，拿到了一个开发者账号，重新打包上传了，这次应该能用很久。

如果遇到#11 的问题，请在系统偏好设置中开启允许任何来源（不明白的话，百度一下你就知道）：
```
sudo spctl –master-disable
```

**Comment by shangrenxi** [comment]
按照网上的给.app重新签名了也不得行，可以开放捐赠作为证书来源。

**Comment by paradiseduo** [comment]
> 按照网上的给.app重新签名了也不得行，可以开放捐赠作为证书来源。

我已经重新打包上传了，目前不考虑开放捐赠，毕竟我只是搬运工，不是创造者😝

**Comment by paradiseduo** [comment]
> 按照网上的给.app重新签名了也不得行，可以开放捐赠作为证书来源。

不行的原因是他的帮助程序的签名需要跟主程序相同，不然安装帮助程序的时候会报证书错误
