### ISSUE TITLE
How to config a ssr server

### ISSUE THREAD

**Issue by engrbee** [paradiseduo/ClashXR#7]
Hi there, I tried to add a ssr server, but it failed.

  name: JP01
  type: ssr
  server: 1.2.3.4
  port: 22990
  cipher: aes-128-ctr
  password: 123456
  obfs: http_simple
  obfsparam: http_simple
  protocolparam: auth_sha1_v4
  protocol: auth_sha1_v4

**Comment by paradiseduo** [comment]
You can not add one server, `clash` need a rule file to use.
You should google to search how to use `clash`.
If you have a subscription address,  you may need this [project](https://github.com/paradiseduo/subweb), it can help you generate rule files.

**Comment by paradiseduo** [comment]
#8
